### ISSUE TITLE
Invalid JSON-LD example

### ISSUE THREAD

**Issue by iherman** [w3c/string-meta#33]
I am looking at the latest (Apr. 4) version of the document which (per https://github.com/WICG/web-share/issues/6#issuecomment-480399962) is about to be published. However, [Example 7](https://w3c.github.io/string-meta/#example-7-json-ld-language-indexing) is incorrect JSON-LD. It should be:

```json
{
  "@context": {
    "example": "http://example.com/example/",
    "title": {
      "@id": "example:title",
      "@container": "@language"
    }
  },
  "@id": "http://example.com/Learning%20Web%20Design",
  "title": { "en"      : "Learning Web Design",
             "ar"      : "التعلم على شبكة الإنترنت التصمي", 
             "ja"      : "Webデザインを学ぶ" ,
             "zh-Hans" : "学习网页设计" 
   }
}
```

**Comment by zoltankonder** [comment]
@iherman you said very recently that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips  from chairing the Internationalization Working Group if this document is going to be published without resolving the issues in the https://github.com/w3c/string-meta/issues/27 

Addison Phillips has conflict of interest and this sting-meta document is only useful on Amazon.com which try to expand its business and push useless standards as requirement! Requirements from the guy who don't even know what is extlang? You gonna be kidding me. But look [he really want it to be fpwd](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat!

I need to write up in HTML a document in 500 different languages and **this [string-meta](https://github.com/w3c/string-meta) document is useless** not only for me but also for the World Wide Web.

It's a shame that this guy is in the group! **He even cried at JSON-LD working group about his meta-string**! 

@r12a @BigBlueHat @ajs6f @gkellogg

**Comment by zoltankonder** [comment]
@iherman you said very recently that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips  from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on Amazon.com which try to expand its business and push useless standards as requirement! 
Requirements from the guy who don't even know what is extlang? You gonna be kidding me. Look [he really want it to be fpwd](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta document is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF in the [string-meta](https://github.com/w3c/string-meta) and than you will have no problem @iherman  also change title of the document as I suggested in https://github.com/w3c/string-meta/issues/27 or throw it straight to the trash! 

At least move this document out of the internationalization working group because it has nothing to do with it!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman you said very recently that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips  from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on Amazon.com which try to expand its business and push useless standards as requirement! 
Requirements from the guy who don't even know what is extlang? You gonna be kidding me. Look [he really want it to be fpwd](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF in the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or throw it straight to the trash! 

At least move this draft out of the internationalization working group because it has nothing to do with it!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman you said very recently that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips  from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on Amazon.com which try to expand its business and push useless standards as requirement! 
Requirements from the guy who don't even know what is extlang? You gonna be kidding me. Look [he really want it to be fpwd](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF from the [string-meta](https://github.com/w3c/string-meta) working draft and than you will also have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or throw this draft straight to the trash! 

At least move the draft out of the internationalization working group because it has nothing to do with it!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman you said very [recently](https://github.com/w3c/string-meta/issues/27#issuecomment-477094333) that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on the products listed on Amazon.com which try to expand its business and pushing for another useless standards as requirement! 
Requirements from the guy who don't even know what is extlang? You gonna be kidding me!
 
A few days ago @aphillips lobbied to [publish String-Meta as first public working draft](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat! You don't deserve this seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF in the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or throw it straight to the trash! 

If still not throwing this to the trash than **move this draft out of the internationalization working group because it has nothing to do with it**!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman you said very [recently](https://github.com/w3c/string-meta/issues/27#issuecomment-477094333) that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on the products listed on Amazon.com which try to expand its business and pushing for another useless standard as requirement! 
Requirements from Addison the guy who don't even know what is extlang? You gonna be kidding me!
 
A few days ago @aphillips lobbied to [publish String-Meta as first public working draft](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat! You don't deserve this seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF in the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or throw it straight to the trash! 

If still not throwing this to the trash than **move this draft out of the internationalization working group because it has nothing to do with it**!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman you said very [recently](https://github.com/w3c/string-meta/issues/27#issuecomment-477094333) that: 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

I going to call both MIT and W3C to remove @aphillips from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful on the products listed on Amazon.com which try to expand its business and pushing for another useless standard as requirement! 
Requirements from Addison the guy who don't even know what is extlang? You gonna be kidding me!
 
A few days ago @aphillips lobbied to [publish String-Meta as first public working draft](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). Cry more Addison before you loose your seat! You don't deserve this seat!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF from the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or throw it straight to the trash! 

If still not throwing this to the trash than **move this draft out of the internationalization working group because it has nothing to do with it**!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman
I fixed [his](https://github.com/w3c/json-ld-syntax/issues/105#issuecomment-445404208) example code and reminding you to [https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing) and [https://www.w3.org/TR/html5/dom.html#the-lang-and-xmllang-attributes](https://www.w3.org/TR/html5/dom.html#the-lang-and-xmllang-attributes)

The code:
```
{
  "@context": {
    "occupation": { "@id": "ex:occupation", "@type": "rdf:HTML", "@container": "@data" },
    "description": "ex:description"
  },
  "name": "Hattori Hanzō",
  "occupation": {
    "ja": "<span lang=\"en\">Ninja in Japanese:<span lang=\"ja\">忍者</span></span>",
    "en": "<span lang=\"en\">Ninja in English:<span lang=\"en\">Ninja</span></span>",
    "cs": "<span lang=\"en\">Ninja in Czech:<span lang=\"cs\">Nindža</span></span>",
    "ar-arb": <span lang=\"en\">Ninja in Arabic:<span lang=\"ar-arb\" dir=\"rtl\">النينجا</span></span>"
  }
} 
```

The `"ar" : "التعلم على شبكة الإنترنت التصمي"` part of your example not only invalid but makes me very angry! See more regarding `@dir` in https://github.com/w3c/string-meta/issues/27! 

Do not forget what you said about string-meta working draft very [recently](https://github.com/w3c/string-meta/issues/27#issuecomment-477094333): 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

Yet here we are again and you complaining about the invalid JSON-LD example by suggesting another invalid...


I going to call both MIT and W3C to remove @aphillips from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful for the products listed on Amazon.com. Amazon try to expand its business and pushing for another useless standard as requirement! 
Requirements from Addison Phillips the guy who don't even know what is extlang? You gonna be kidding me!
 
A few days ago @aphillips **lobbied to** [**publish String-Meta as first public working draft**](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). In my opinion **Addison Phillips must be kicked out of the Internationalization Working Group** for this move! While he had know there are serious issues with this document he fraudulently requested publication!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF from the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or **throw it straight to the trash**! 

If still not throwing this to the trash than **move this draft out of the internationalization working group because it has nothing to do with it**!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by zoltankonder** [comment]
@iherman
I fixed [his](https://github.com/w3c/json-ld-syntax/issues/105#issuecomment-445404208) example code and reminding you to [https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing](https://www.w3.org/International/techniques/authoring-html.en?open=language&open=textprocessing#textprocessing) and [https://www.w3.org/TR/html5/dom.html#the-lang-and-xmllang-attributes](https://www.w3.org/TR/html5/dom.html#the-lang-and-xmllang-attributes)

The code:
```
{
  "@context": {
    "occupation": { "@id": "ex:occupation", "@type": "rdf:HTML", "@container": "@data" },
    "description": "ex:description"
  },
  "name": "Hattori Hanzō",
  "occupation": {
    "ja": "<span lang=\"en\">Ninja in Japanese:<span lang=\"ja\">忍者</span></span>",
    "en": "<span lang=\"en\">Ninja in English:<span lang=\"en\">Ninja</span></span>",
    "cs": "<span lang=\"en\">Ninja in Czech:<span lang=\"cs\">Nindža</span></span>",
    "ar-arb": <span lang=\"en\">Ninja in Arabic:<span lang=\"ar-arb\" dir=\"rtl\">النينجا</span></span>"
  }
} 
```

The `"ar" : "التعلم على شبكة الإنترنت التصمي"` part of your example not only invalid but makes me very angry! See more regarding `@dir` in https://github.com/w3c/string-meta/issues/27! 

Do not forget what you said about string-meta working draft very [recently](https://github.com/w3c/string-meta/issues/27#issuecomment-477094333): 
> **actually, the emphasis is on JSON at large rather than JSON-LD. In other words, the draft is very useful for JSON based specifications that are not bound to JSON-LD/RDF** 

Yet here we are again and you complaining about the invalid JSON-LD example by suggesting another invalid...


I going to call both MIT and W3C to remove @aphillips from chairing the Internationalization Working Group if this document is going to be published without resolving https://github.com/w3c/string-meta/issues/27!

Addison Phillips has conflict of interest and this sting-meta document is only useful for the products listed on Amazon.com. Amazon try to expand its business and pushing for another useless standard as requirement! 
Requirements from Addison Phillips the guy who don't even know what is extlang? You gonna be kidding me!
 
A few days ago @aphillips **lobbied to** [**publish String-Meta as first public working draft**](https://lists.w3.org/Archives/Public/www-international/2019AprJun/0004.html). In my opinion **Addison Phillips must be kicked out from the Internationalization Working Group** for this move! While he had know there are serious issues with this document he fraudulently requested publication!

I need to write up a document in HTML in more than 500 different languages and the **string-meta working draft is useless** to speed up or help in any way in this process and so it is useless for the World Wide Web! 

I request again to remove all references to JSON-LD and RDF from the [string-meta](https://github.com/w3c/string-meta) working draft and than you will have no problem @iherman! I request again to change title as I suggested in https://github.com/w3c/string-meta/issues/27 or **throw it straight to the trash**! 

If still not throwing this to the trash than **move this draft out of the internationalization working group because it has nothing to do with it**!

@BigBlueHat @r12a @ajs6f @rubensworks

**Comment by r12a** [comment]
The commit at https://github.com/w3c/string-meta/commit/2c5311bf296ab1ab2dddc54ce34d00152c094bfd fixes Example 7.
It also seeks to clarify the scope of the document.
I'm therefore closing this issue.
